{
  "language": "node_js",
  "node_js": "node",
  "install": [
    "npm install",
    "npm --prefix ./node_modules/primo-explore-devenv install ./node_modules/primo-explore-devenv",
    "npm install -g gulp"
  ],
  "before_script": [
    "node ./node_modules/primo-explore-devenv/gulp/copyDir.js --from ./ --to ./node_modules/primo-explore-devenv/primo-explore/custom/primo-explore-location-item-after-google-maps-demo",
    "./node_modules/primo-explore-devenv/gulp run --view primo-explore-location-item-after-google-maps-demo --proxy http://primo-demo.exlibrisgroup.com:1701",
    "./node_modules/primo-explore-devenv/gulp custom-css",
    "./node_modules/primo-explore-devenv/gulp custom-js"
  ],
  "script": [
    "protractor ./tests/conf.js"
  ],
  "os": "linux"
}

